# Generated by Django 2.2.5 on 2019-09-16 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190916_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Added',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 5, 48, 37, 98681)),
        ),
    ]
