# Generated by Django 2.2.5 on 2019-09-16 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190916_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
