# Generated by Django 2.2.5 on 2019-09-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190916_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Added',
            new_name='added_date',
        ),
    ]
